name: Continuous Deploy

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed
    branches: [main]
    
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pull latest image
        run: |
          docker pull ghcr.io/${{ github.repository }}:dev
          
      - name: Stop existing container
        run: |
          docker stop echo-rss || true
          docker rm echo-rss || true
          
      - name: Start container
        run: |
          docker run -d \
            --name echo-rss \
            -p 11299:11299 \
            -v $(pwd)/resources:/app/resources \
            ghcr.io/${{ github.repository }}:dev
