name: Continuous Deploy

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4

      - name: Install frontend dependencies
        working-directory: ./web
        run: |
          pnpm install
          
      - name: Build frontend
        working-directory: ./web
        run: |
          pnpm run build
          
      - name: Install backend dependencies
        working-directory: ./server
        run: |
          go mod tidy
          
      - name: Build backend
        working-directory: ./server
        run: |
          go build -o echo-rss
          
      - name: Stop existing service
        run: |
          pm2 delete echo-rss || true
          
      - name: Start service
        working-directory: ./server
        run: |
          pm2 start ./echo-rss --name echo-rss
