name: Continuous Deploy

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed
    branches: [main]
    
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Pull latest image
        run: |
          sudo docker pull ghcr.io/ray-d-song/echorss:dev
          
      - name: Stop existing container
        run: |
          sudo docker stop echorss || true
          sudo docker rm echorss || true
          
      - name: Start container
        run: |
          sudo docker run -d \
            --name echorss \
            -p 11299:11299 \
            -v ~/docker/echorss:/resources \
            ghcr.io/ray-d-song/echorss:dev
