name: Continuous Deploy

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed
    branches: [main]
    
jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Pull latest image
        run: |
          sudo docker pull ghcr.io/ray-d-song/echo-rss:dev
          
      - name: Stop existing container
        run: |
          sudo docker stop echo-rss || true
          sudo docker rm echo-rss || true
          
      - name: Start container
        run: |
          sudo docker run -d \
            --name echo-rss \
            -p 11299:11299 \
            -v $(pwd)/resources:/app/resources \
            ghcr.io/ray-d-song/echo-rss:dev
